location             = "East US"
resource_group_name  = "test-resource-group"
storage_account_name = "teststorageaccount"
app_service_plan_name = "test-app-service-plan"
app_service_name     = "test-app-service"
function_app_name    = "test-function-app"
